version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "[dependabot]"
      include: "scope"
    open-pull-requests-limit: 3

  - package-ecosystem: terraform
    directory: "pipeline"
    schedule:
      interval: daily
    commit-message:
      prefix: "[dependabot]"
      include: "scope"
    open-pull-requests-limit: 3
